# Generated by Django 2.2.12 on 2021-01-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_active',
        ),
    ]
